export const CREATE_REMINDER = "REMINDERS/CREATE_REMINDER";
export const FETCH_REMINDERS = "REMINDERS/FETCH_REMINDERS";
export const FETCH_REMINDER = "REMINDERS/FETCH_REMINDER";
export const SHOW_LOADER = "REMINDERS/SHOW_LOADER";
export const HIDE_LOADER = "REMINDERS/HIDE_LOADER";
export const SET_ERROR = "REMINDERS/SET_ERROR";
export const CLEAR_ERROR = "REMINDERS/CLEAR_ERROR";