export const CREATE_TASK = "TASKS/CREATE_TASK";
export const SHOW_CREATE_LOADER = "TASKS/SHOW_CREATE_LOADER";
export const HIDE_CREATE_LOADER = "TASKS/HIDE_CREATE_LOADER";
export const SET_CREATE_ERROR = "TASKS/SET_CREATE_ERROR";
export const CLEAR_CREATE_ERROR = "TASKS/CLEAR_CREATE_ERROR";

export const DELETE_TASK = "TASKS/DELETE_TASK";
export const SHOW_DELETE_LOADER = "TASKS/SHOW_DELETE_LOADER";
export const HIDE_DELETE_LOADER = "TASKS/HIDE_DELETE_LOADER";
export const SET_DELETE_ERROR = "TASKS/SET_DELETE_ERROR";
export const CLEAR_DELETE_ERROR = "TASKS/CLEAR_DELETE_ERROR";

export const UPDATE_TASK = "TASKS/UPDATE_TASK";

export const CHANGE_TASK_STATUS = "TASKS/CHANGE_TASK_STATUS";


export const FETCH_TASKS = "TASKS/FETCH_TASKS";
export const SHOW_LOADER = "TASKS/SHOW_LOADER";
export const HIDE_LOADER = "TASKS/HIDE_LOADER";
export const SET_ERROR = "TASKS/SET_ERROR";
export const CLEAR_ERROR = "TASKS/CLEAR_ERROR";

export const SCHEDULE_TASKS = "TASKS/SCHEDULE_TASKS"